//
//  MessageConstants.swift
//  Stando
//
//  Created by Max Wo on 28/7/2023.
//

import SwiftUI

struct MessageConstants {
    static let sitMessages = [
        "Take a comfortable seat and relax. You deserve a moment of tranquility.",
        "Find a cozy spot to sit down and let your stress melt away.",
        "Sitting down can be a peaceful moment to reflect and recharge.",
        "Rest your feet and sit for a while. It's the perfect time to unwind.",
        "Enjoy the pleasure of sitting and taking a breather. You've earned it.",
        "Sitting down doesn't mean being idle. It's a chance to gather your thoughts and plan ahead.",
        "Grab a seat and enjoy the view. Sometimes, the best ideas come when you're seated comfortably.",
        "Give your legs a break and settle into a chair. Your body will thank you.",
        "Take a moment to sit back and relax. Your well-being is a priority.",
        "Sitting comfortably allows you to focus on the present moment. Enjoy the stillness.",
        "Sit down, take a deep breath, and let go of any tension you may be carrying.",
        "Seated or standing, both are important. Today, take a moment to sit and be mindful.",
        "Find a place to sit down and enjoy a few minutes of peaceful solitude.",
        "Sitting down can be an opportunity to meditate and find inner calm.",
        "Take a seat and read a good book. It's a wonderful way to escape and unwind.",
        "Appreciate the simple act of sitting down, and savor the comfort it brings.",
        "Sitting allows you to engage with your surroundings on a deeper level. Embrace the moment.",
        "Even in stillness, you can feel a sense of contentment while seated comfortably.",
        "Enjoy the freedom of sitting down and let your mind wander wherever it pleases.",
        "Taking a seat isn't a sign of weakness; it's a chance to gather strength and move forward with clarity.",
        "Find a comfortable spot to sit and relax. It's time to unwind and destress.",
        "Sitting down can be a moment of tranquility amidst a busy day. Enjoy the calm.",
        "Take a seat and let your thoughts wander. Some of the best ideas come when you're seated comfortably.",
        "Sit back, take a deep breath, and appreciate the beauty of the present moment.",
        "Sitting allows you to take a break from the chaos and enjoy a moment of serenity.",
        "Find solace in a seat, where you can collect your thoughts and find inner peace.",
        "Sit down, sip some tea, and let go of the worries that weigh you down.",
        "Seated or standing, both are important. Today, take a moment to sit and be mindful.",
        "Embrace the joy of sitting down and savor the simple pleasures of life.",
        "Take a seat and immerse yourself in a captivating book or story.",
        "Sitting comfortably helps you focus on your tasks with clarity and precision.",
        "Give your body the rest it deserves. Take a seat and recharge your energy.",
        "Seated, you can witness the world from a different perspective. Enjoy the view!",
        "Sitting can be a moment of reflection and gratitude. Take a moment to appreciate all you have.",
        "Sit down and let the gentle rhythm of your breath anchor you to the present.",
        "Your chair is your sanctuary. Take a moment to embrace its comfort and support.",
        "Sitting allows you to fully enjoy the delicious meal you've prepared. Bon appétit!",
        "Take a seat, close your eyes, and visualize your dreams becoming a reality.",
        "Sitting down doesn't mean being inactive. It's a chance to focus and plan your next move.",
        "Find a seat, and let the world slow down for a moment while you catch your breath.",
        "Give your feet a break, and let yourself sink into the coziness of sitting down.",
        "Sitting is an opportunity to connect with loved ones, sharing stories and laughter.",
        "Take a moment to sit, relax, and appreciate the beauty of the world around you.",
        "Even in stillness, you can find peace. Embrace the calmness of sitting down.",
        "Sit down, let your thoughts wander, and discover the power of daydreaming.",
        "Take a seat and treat yourself to a well-deserved moment of self-care.",
        "A comfortable seat can be your refuge during a hectic day. Enjoy its embrace.",
        "Sitting down lets you appreciate the little things in life that often go unnoticed.",
        "The art of sitting lies in appreciating the stillness amidst life's constant motion.",
        "In a world that never stops moving, sit down and let yourself be fully present in the moment."
    ]

    static let standMessages = [
        "It's time to stand up and stretch! Your body will thank you for the break.",
        "A quick reminder to stand up and move around for a few minutes. Your health matters!",
        "Sitting for too long can take a toll on your body. Take a stand and give your muscles a breather.",
        "Stretch your legs, stand tall, and revitalize your energy!",
        "Sitting is great, but standing is even better! Take a moment to stand up and refresh.",
        "Rise and shine! Standing up increases blood flow and boosts productivity.",
        "Stand up and take a mini dance break! Your body and mood will appreciate it.",
        "Just a gentle nudge to stand up and improve your posture. Your spine will thank you.",
        "Break the sitting cycle! Stand up, walk around, and come back feeling rejuvenated.",
        "Standing is a simple way to increase your metabolism and feel more active.",
        "Your body craves movement. Stand up and get your blood flowing.",
        "You're not meant to be glued to your chair. Stretch those legs and stand tall!",
        "Sitting for hours can lead to stiffness. Take a moment to stand up and loosen up.",
        "Boost your energy levels by standing up and taking a quick breather.",
        "You've been sitting like a champ! Now, take a standing ovation for your health.",
        "Get up, stand up! Stand up for your health!",
        "Remember, sitting is optional. Stand up and embrace a healthier lifestyle.",
        "A standing break can clear your mind and improve focus. Give it a try!",
        "Your body loves movement. Stand up, move around, and stay active.",
        "Sitting is just a habit. Break it by standing up and embracing a more dynamic day!",
        "Feeling a bit sluggish? Stand up and get that blood flowing for an instant energy boost!",
        "Time to rise and shine! Stand tall and conquer the day.",
        "A gentle reminder to stand up and take a mini-break. Your body will thank you for it!",
        "Stretch those legs and stand up for better circulation and reduced muscle stiffness.",
        "Your chair will miss you, but your body will love you for standing up and moving around!",
        "Taking a stand for your health means taking a stand right now! Get up and stretch.",
        "Sitting for extended periods can lead to back pain. Stand up and give your back some relief.",
        "Ready for a change of perspective? Stand up and see the world from a different angle.",
        "Don't let the day pass you by while seated. Stand up, seize the moment, and make it yours!",
        "Unlock your body's potential by standing up and embracing a more active lifestyle.",
        "Your future self will thank you for taking regular standing breaks. Give it a go!",
        "Don't just sit there – stand up, shake it off, and feel the stress fade away.",
        "Why sit when you can stand? Let your body stretch and your mind refresh.",
        "Every hour, let's make a deal – stand up, move around, and recharge your zeal!",
        "Take a break from sitting and treat yourself to a quick standing meditation.",
        "Feeling stuck? Stand up, take a deep breath, and find the inspiration you seek.",
        "Make standing a habit, and you'll soon discover the wonders it does for your well-being.",
        "A simple act of standing up can lead to big improvements in your overall health.",
        "Stand up and take a moment to appreciate the amazing machine that is your body.",
        "Standing up is the first step toward making positive changes in your daily routine.",
        "Your body craves movement – give it what it wants by standing up and being active.",
        "No more slouching! Stand tall, radiate confidence, and own your presence.",
        "You are meant to move, not stay sedentary. Stand up and embrace your vitality!",
        "Each time you stand up, you're investing in a healthier and happier future.",
        "Feeling a little foggy? Stand up, get some fresh air, and clear your mind.",
        "Your muscles are eager for a break. Stand up and show them some love.",
        "Sitting is fine in moderation, but standing adds a dynamic touch to your day.",
        "A small act of standing now can lead to big rewards in the long run. Be proactive!",
        "Experience the freedom of standing up and let your creativity soar.",
        "Your body is designed to move. Stand up, take a stroll, and embrace your natural grace."
    ]
}
